### ISSUE TITLE
gitignore の指定を削除

### ISSUE THREAD

**Issue by sundaycrafts** [mediascience-gk/dramafam#10]
使いたいプロジェクトはあるので、基本的に IDE 周りは ignore しない方がいいです。するなら自分のマシンの設定でした方が良い

以下 `~/.gitconfig` の設定。この設定をすると、 `~/.gitignore` がプロジェクトなどにかかわらずすべて ignore されるようになります

```
[core]
	excludesFile = ~/.gitignore
```

https://github.com/mediasciencejp/review-system/blob/9611b4fff88d5527511bb1a51de9c59d4b80b23d/.gitignore#L1

**Comment by mediasciencejp** [comment]
完了いたしました。
