### ISSUE TITLE
法人名のオーガニゼーションの作成おねがいします

### ISSUE THREAD

**Issue by sundaycrafts** [mediascience-gk/dramafam#8]
@sundaycrafts の invite もお願いします。

1. オーガニゼーションの作成

https://docs.github.com/ja/organizations/collaborating-with-groups-in-organizations/creating-a-new-organization-from-scratch

2. リポジトリの移動

https://docs.github.com/ja/repositories/creating-and-managing-repositories/transferring-a-repository

**Comment by mediasciencejp** [comment]
完了いたしました。
