### ISSUE TITLE
リポジトリの Readme おねがいします

### ISSUE THREAD

**Issue by sundaycrafts** [mediascience-gk/dramafam#9]
## 記述して欲しい内容 (順不同)

1. 公開先 (URL)
2. 目的
3. 検証環境のセットアップ方法 (例: 「バックエンドを起動させてからフロントエンドを起動させてください」や「DB の seed 注入」など)

**Comment by mediasciencejp** [comment]
まだ完全な出来とは程遠いですが、ひとまず完了いたしました。今後、適宜更新していきます。
